name: Build tests

on: [pull_request]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        path: ['non-vpath', 'vpath']
    steps:
    - name: Install dependencies
      run: brew install libevent hwloc autoconf automake libtool
    - name: Git clone OpenPMIx
      uses: actions/checkout@v3
      with:
            submodules: recursive
            repository: openpmix/openpmix
            path: openpmix/master
            ref: master
    - name: Build OpenPMIx
      run: |
        cd openpmix/master
        ./autogen.pl

        ./configure --prefix=$RUNNER_TEMP/pmixinstall
        make -j
        make install
    - name: Git clone PMI shim
      uses: actions/checkout@v3
      with:
            clean: false
    - name: Build PMI shim
      run: |
        ./autogen.sh

        if test "${{ matrix.path }}" = vpath; then
            mkdir build
            cd build
            ../configure --prefix=$RUNNER_TEMP/shim --with-pmix=$RUNNER_TEMP/pmixinstall
        else
            ./configure --prefix=$RUNNER_TEMP/shim --with-pmix=$RUNNER_TEMP/pmixinstall
        fi
        make -j
        make install
        make uninstall

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ['non-vpath', 'vpath']
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends software-properties-common libhwloc-dev libevent-dev
    - name: Git clone OpenPMIx
      uses: actions/checkout@v3
      with:
            submodules: recursive
            repository: openpmix/openpmix
            path: openpmix/master
            ref: master
    - name: Build OpenPMIx
      run: |
        cd openpmix/master
        ./autogen.pl
        ./configure --prefix=$RUNNER_TEMP/pmixinstall
        make -j
        make install
    - name: Git clone PMI shim
      uses: actions/checkout@v3
      with:
            clean: false
    - name: Build PMI shim
      run: |
        ./autogen.sh

        if test "${{ matrix.path }}" = vpath; then
            mkdir build
            cd build
            ../configure --prefix=$RUNNER_TEMP/shim --with-pmix=$RUNNER_TEMP/pmixinstall
        else
            ./configure --prefix=$RUNNER_TEMP/shim --with-pmix=$RUNNER_TEMP/pmixinstall
        fi
        make -j
        make install
        make uninstall

